#if defined(ARDUINO) && ARDUINO >= 100
    #include "Arduino.h"
#else
    #include "WProgram.h"
#endif
#include "Event.h"


/**
 * Event
 * 
 * Events are generated by buttons or external (wireless) d3vices.
 * Events are stored as bools for one tick,
 * optionally processed by Game,
 * then cleared at the start of the next tick.
 * 
 */
Event::Event()
{
}

void Event::update() {
  _isPressEvent = 0;
  _isReleaseEvent = 0;
  _isLongHoldEvent = 0;
  _isLongReleaseEvent = 0;
  _isDoublePressEvent = 0;
  _isDoubleLongHoldEvent = 0;
  _isDoubleReleaseEvent = 0;
  _isDoubleLongReleaseEvent = 0;
}

void Event::registerPressEvent(bool teamNumber) {
  _isPressEvent = 1;
}

void Event::registerReleaseEvent(bool teamNumber) {
  
}

void Event::registerLongHoldEvent(bool teamNumber) {
  
}

void Event::registerLongReleaseEvent(bool teamNumber) {
  
}

